### ISSUE TITLE
Vanishing  Player

### ISSUE THREAD

**Issue by twobraids** [lmorchard/fx-maze#25]
about five minutes into game play, just after crossing into a new tiled region, the player and the path marking vanish, never to be seen again.  see this example: https://youtu.be/GY6qGw71B1w?t=4m39s

**Comment by twobraids** [comment]
console logging is saying "NS_ERROR_NOT_AVAILABLE" on this line:

``` javascript
        ctx.drawImage(map.tiles[tileKey], 0, 0, map.tileWidth, map.tileHeight, x, y, map.tileWidth * camera.z, map.tileHeight * camera.z);
```

**Comment by twobraids** [comment]
it's looking for a tile that doesn't exist  "8x1"

**Comment by lmorchard** [comment]
Oh! Heh, I was only looking for negative row/col numbers and not ones over the limit of rows & cols. Guess I haven't quite playtested into those regions of the maze since I got the tiling working
