### ISSUE TITLE
Solution hints?

### ISSUE THREAD

**Issue by lmorchard** [lmorchard/fx-maze#7]
Should this have a way to provide hints toward a solution? If so, how could they be presented? Easy way is to just show a line to follow. More interesting way might be to make a "ghost" appear that the player can follow for a limited time to at least get them on the right track.

**Comment by twobraids** [comment]
I'm thinking of a "mood" indicator on a corner of the screen.  We can use a hidden solution map that could be used to detect when the player is off the solution path.  The longer the player is off the correct path, the more "sad" the mood indicator gets.  On the first wrong turn, the mood indicator make a subtle shift in color.  The color change then slowly deepens over time until the player has returned to the correct path.

**Comment by lmorchard** [comment]
1a9a1c801b019c34645b5aa3d727a8b80814bd88
